export const info_blog = [
  {
    name_id: 1,
    image: "/assets/img_blog/blog_1.webp",
    title: "Quit smoking: 10 ways to resist tobacco cravings",
    brief_description:
      "Tobacco cravings can be debilitating for anyone trying to quit smoking. Follow these tips to reduce and combat these urges.",
    description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction. 1- Use nicotine replacements Nicotine replacement is one of the effective ways to help you quit smoking. You can consult your doctor to use nicotine in the form of a nasal spray or inhaler, or use nicotine-containing gum, patches and lozenges without a prescription. There are also medications such as bupropion and varenicline that can be used without a prescription. 2- Avoid triggers The desire to smoke becomes stronger in places where you are accustomed to smoking or in moments when you feel stressed. You should identify these triggers and make a plan to avoid them or deal with them without smoking. Find other ways to entertain or relieve stress, such as reading or drawing. 3- Postponing gratification If you feel a strong desire to smoke, try postponing it for 10 minutes. During this time, do distracting activities, such as going to a public place where smoking is prohibited. 4- Use chewing gum You can combat the urge to smoke by chewing. Choose sugarless gum or eat raw carrots, nuts or sunflower seeds. 5- Avoid thinking about “just one cigarette.” Avoid the idea of smoking one cigarette because it often leads to resuming the smoking habit completely. 6- Practice physical activity Physical activities help improve your mood and overall health. Do short exercise sessions when you feel the urge to smoke. Even doing simple exercises in the office or home can help relieve cravings. 7- Adopt relaxation techniques Use relaxation techniques such as deep breathing, muscle relaxation, yoga, and visualization to overcome stress that can be a trigger for smoking. 8- Find support Don't hesitate to ask for support from family members and friends or join support groups. Social support can play a big role in achieving success. 9- Take advantage of online support Join online smoking cessation programs or search for online resources that offer support and personal experiences for people seeking to quit smoking. 10- Remind yourself of the benefits of quitting smoking",
    date: "11-3-2023",
  },
  {
    name_id: 2,
    image: "/assets/img_blog/blog_2.webp",
    title:
      "Overcoming Smoking Addiction: 10 Strategies to Overcome Tobacco Cravings",
    brief_description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction.",
    description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction. 1- Use nicotine replacements Nicotine replacement is one of the effective ways to help you quit smoking. You can consult your doctor to use nicotine in the form of a nasal spray or inhaler, or use nicotine-containing gum, patches and lozenges without a prescription. There are also medications such as bupropion and varenicline that can be used without a prescription. 2- Avoid triggers The desire to smoke becomes stronger in places where you are accustomed to smoking or in moments when you feel stressed. You should identify these triggers and make a plan to avoid them or deal with them without smoking. Find other ways to entertain or relieve stress, such as reading or drawing. 3- Postponing gratification If you feel a strong desire to smoke, try postponing it for 10 minutes. During this time, do distracting activities, such as going to a public place where smoking is prohibited. 4- Use chewing gum You can combat the urge to smoke by chewing. Choose sugarless gum or eat raw carrots, nuts or sunflower seeds. 5- Avoid thinking about “just one cigarette.” Avoid the idea of smoking one cigarette because it often leads to resuming the smoking habit completely. 6- Practice physical activity Physical activities help improve your mood and overall health. Do short exercise sessions when you feel the urge to smoke. Even doing simple exercises in the office or home can help relieve cravings. 7- Adopt relaxation techniques Use relaxation techniques such as deep breathing, muscle relaxation, yoga, and visualization to overcome stress that can be a trigger for smoking. 8- Find support Don't hesitate to ask for support from family members and friends or join support groups. Social support can play a big role in achieving success. 9- Take advantage of online support Join online smoking cessation programs or search for online resources that offer support and personal experiences for people seeking to quit smoking. 10- Remind yourself of the benefits of quitting smoking",
    date: "11-3-2023",
  },
  {
    name_id: 3,
    image: "/assets/img_blog/blog_3.webp",
    title:
      "Overcoming Smoking Addiction: 10 Strategies to Overcome Tobacco Cravings",
    brief_description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction.",
    description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction. 1- Use nicotine replacements Nicotine replacement is one of the effective ways to help you quit smoking. You can consult your doctor to use nicotine in the form of a nasal spray or inhaler, or use nicotine-containing gum, patches and lozenges without a prescription. There are also medications such as bupropion and varenicline that can be used without a prescription. 2- Avoid triggers The desire to smoke becomes stronger in places where you are accustomed to smoking or in moments when you feel stressed. You should identify these triggers and make a plan to avoid them or deal with them without smoking. Find other ways to entertain or relieve stress, such as reading or drawing. 3- Postponing gratification If you feel a strong desire to smoke, try postponing it for 10 minutes. During this time, do distracting activities, such as going to a public place where smoking is prohibited. 4- Use chewing gum You can combat the urge to smoke by chewing. Choose sugarless gum or eat raw carrots, nuts or sunflower seeds. 5- Avoid thinking about “just one cigarette.” Avoid the idea of smoking one cigarette because it often leads to resuming the smoking habit completely. 6- Practice physical activity Physical activities help improve your mood and overall health. Do short exercise sessions when you feel the urge to smoke. Even doing simple exercises in the office or home can help relieve cravings. 7- Adopt relaxation techniques Use relaxation techniques such as deep breathing, muscle relaxation, yoga, and visualization to overcome stress that can be a trigger for smoking. 8- Find support Don't hesitate to ask for support from family members and friends or join support groups. Social support can play a big role in achieving success. 9- Take advantage of online support Join online smoking cessation programs or search for online resources that offer support and personal experiences for people seeking to quit smoking. 10- Remind yourself of the benefits of quitting smoking",
    date: "11-3-2023",
  },
  {
    name_id: 4,
    image: "/assets/img_blog/blog_4.webp",
    title:
      "Overcoming Smoking Addiction: 10 Strategies to Overcome Tobacco Cravings",
    brief_description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction.",
    description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction. 1- Use nicotine replacements Nicotine replacement is one of the effective ways to help you quit smoking. You can consult your doctor to use nicotine in the form of a nasal spray or inhaler, or use nicotine-containing gum, patches and lozenges without a prescription. There are also medications such as bupropion and varenicline that can be used without a prescription. 2- Avoid triggers The desire to smoke becomes stronger in places where you are accustomed to smoking or in moments when you feel stressed. You should identify these triggers and make a plan to avoid them or deal with them without smoking. Find other ways to entertain or relieve stress, such as reading or drawing. 3- Postponing gratification If you feel a strong desire to smoke, try postponing it for 10 minutes. During this time, do distracting activities, such as going to a public place where smoking is prohibited. 4- Use chewing gum You can combat the urge to smoke by chewing. Choose sugarless gum or eat raw carrots, nuts or sunflower seeds. 5- Avoid thinking about “just one cigarette.” Avoid the idea of smoking one cigarette because it often leads to resuming the smoking habit completely. 6- Practice physical activity Physical activities help improve your mood and overall health. Do short exercise sessions when you feel the urge to smoke. Even doing simple exercises in the office or home can help relieve cravings. 7- Adopt relaxation techniques Use relaxation techniques such as deep breathing, muscle relaxation, yoga, and visualization to overcome stress that can be a trigger for smoking. 8- Find support Don't hesitate to ask for support from family members and friends or join support groups. Social support can play a big role in achieving success. 9- Take advantage of online support Join online smoking cessation programs or search for online resources that offer support and personal experiences for people seeking to quit smoking. 10- Remind yourself of the benefits of quitting smoking",
    date: "11-3-2023",
  },
  {
    name_id: 5,
    image: "/assets/img_blog/blog_5.webp",
    title:
      "Overcoming Smoking Addiction: 10 Strategies to Overcome Tobacco Cravings",
    brief_description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction.",
    description:
      "The urge to smoke can be a major challenge for anyone seeking to quit this harmful habit. But there are several strategies that can help you resist that urge and overcome smoking addiction. 1- Use nicotine replacements Nicotine replacement is one of the effective ways to help you quit smoking. You can consult your doctor to use nicotine in the form of a nasal spray or inhaler, or use nicotine-containing gum, patches and lozenges without a prescription. There are also medications such as bupropion and varenicline that can be used without a prescription. 2- Avoid triggers The desire to smoke becomes stronger in places where you are accustomed to smoking or in moments when you feel stressed. You should identify these triggers and make a plan to avoid them or deal with them without smoking. Find other ways to entertain or relieve stress, such as reading or drawing. 3- Postponing gratification If you feel a strong desire to smoke, try postponing it for 10 minutes. During this time, do distracting activities, such as going to a public place where smoking is prohibited. 4- Use chewing gum You can combat the urge to smoke by chewing. Choose sugarless gum or eat raw carrots, nuts or sunflower seeds. 5- Avoid thinking about “just one cigarette.” Avoid the idea of smoking one cigarette because it often leads to resuming the smoking habit completely. 6- Practice physical activity Physical activities help improve your mood and overall health. Do short exercise sessions when you feel the urge to smoke. Even doing simple exercises in the office or home can help relieve cravings. 7- Adopt relaxation techniques Use relaxation techniques such as deep breathing, muscle relaxation, yoga, and visualization to overcome stress that can be a trigger for smoking. 8- Find support Don't hesitate to ask for support from family members and friends or join support groups. Social support can play a big role in achieving success. 9- Take advantage of online support Join online smoking cessation programs or search for online resources that offer support and personal experiences for people seeking to quit smoking. 10- Remind yourself of the benefits of quitting smoking",
    date: "11-3-2023",
  },
];
